### GET health endpoint
GET http://127.0.0.1:9000/actuator/health
X-Request-Id: theId12345
ERIC-Identity: 67ZeMsvAEgkBWs7tNKacdrPvOmQ
ERIC-Identity-Type: key
ERIC-Authorised-Key-Roles: *
Content-Type: application/json

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### POST a letter request request to example server
POST http://127.0.0.1:8081/letter
X-Request-Id: theId12345
ERIC-Identity: 67ZeMsvAEgkBWs7tNKacdrPvOmQ
ERIC-Identity-Type: key
ERIC-Authorised-Key-Roles: *
Content-Type: application/json

{
    "sender_details": {
        "app_id": "",
        "reference": "",
        "name": "",
        "user_id": "",
        "email_address": "john.doe@company3.domaind.extra.com"
    },
    "recipient_details": {
        "name": "",
        "physical_address": {
            "address_line_1": "",
            "address_line_2": "",
            "address_line_3": "",
            "address_line_4": "",
            "address_line_5": "",
            "address_line_6": "",
            "address_line_7": ""
        }
    },
    "letter_details": {
        "template_id": "",
        "template_version": 1,
        "personalisation_details": {
            "letter_reference": "0123456789",
            "company_name": "BIG SHOP LTD",
            "company_id": "9876543210",
            "psc_type": "25%"
        }
    },
    "created_at": "2025-01-01T00:00:00.000Z"
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###